name: React CI/CD to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install openvpn -y

      - name: Create VPN 1 config from existing secrets
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn1.conf
          echo "${{ secrets.VPN_CREDS }}" > vpn1.txt
          echo "auth-user-pass vpn1.txt" >> vpn1.conf
          echo "redirect-gateway def1" >> vpn1.conf

      - name: Create VPN 2 config
        run: |
          echo "${{ secrets.VPN2_CONFIG }}" > vpn2.conf
          echo "${{ secrets.VPN2_CREDS }}" > vpn2.txt
          echo "auth-user-pass vpn2.txt" >> vpn2.conf
          echo "redirect-gateway def1" >> vpn2.conf

      - name: Check IP before VPN
        run: |
          echo "Public IP before VPN:"
          curl ifconfig.me

      - name: Connect to VPN (fallback if VPN 1 fails)
        run: |
          echo "Attempting VPN 1..."
          sudo openvpn --config vpn1.conf --daemon
          sleep 10
          curl --max-time 10 ifconfig.me || {
            echo "VPN 1 failed, switching to VPN 2..."
            sudo pkill openvpn
            sudo openvpn --config vpn2.conf --daemon
            sleep 10
            curl --max-time 10 ifconfig.me || {
              echo "Both VPNs failed. Exiting CI."
              exit 1
            }
          }

      - name: Check IP after VPN
        run: |
          echo "Public IP after VPN:"
          curl ifconfig.me

      - name: Debug VPN logs
        run: |
          echo "OpenVPN logs (filtered):"
          sudo cat /var/log/syslog | grep openvpn || echo "No VPN logs found"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/react-frontend
            git pull origin main
            npm install
            npm run build
            pm2 restart react-app || echo "PM2 process not found"
